name: energonauthapp
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  firebase_auth:
  google_sign_in: ^4.0.0
  firebase_core: ^0.4.4
  firebase_dynamic_links: ^0.5.1
  uuid: ^2.0.2

dev_dependencies:
  pedantic: ^1.8.0
  flutter_driver:
    sdk: flutter
  test: any
  e2e: ^0.6.1

flutter:
  uses-material-design: true
